### ISSUE TITLE
[bug fix] Bug in Readme file

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [karunakaran186/KAVI-voice-Assitant#108]
Hey there , Greeting's  of the day !! 
As u know that the readme is one of the most important file that reflect's ur repo work and what all it contain's in it . 
If this will wrong then it gave bad compact on the organisation . 

There are lot's of Grammatical error and space as well as speeling mistake  in your readme.md file , kindly assign this issue to me so that i can improve the readme file .

**Comment by karunakaran186** [comment]
Yes sure! You can work on that issue bro

**Comment by Vikash-8090-Yadav** [comment]
Am a GSSOC'22 CONTRIBUTOR ..plss add that label and level ..

Thank u 😄

**Comment by karunakaran186** [comment]
sure!!! :)
