### ISSUE TITLE
Broken Link in Readme File

### ISSUE THREAD

**Issue by Rakesh9100** [karunakaran186/KAVI-voice-Assitant#110]
Hello,
I would like to configure that one of the link named "Issues" is not opening the issues of this repo.
## On clicking the below link, it navigates to :
![1](https://user-images.githubusercontent.com/73993775/161399295-b4309bb0-a2ad-4b11-a1a2-219b0a09db08.png)<br>
## This page and not the defined project owners' repo. <br>
![2](https://user-images.githubusercontent.com/73993775/161399296-94c1ce5b-64f6-4369-85e4-a280aa6f568f.png)

So, I would like to fix it.
Working as a GSSoC22 Contributor !!

**Comment by karunakaran186** [comment]
Yes you can work on that issue bro!
