### ISSUE TITLE
Defining Task : Tells user about something, by searching on the internet (e.g 'Kavi tell me about oranges')

### ISSUE THREAD

**Issue by ravencode69** [karunakaran186/KAVI-voice-Assitant#12]
Expected Output:- Kavi searches the particular question over the web in order to find her answers. 
user:- "Kavi tell me about XYZ"

<img src="https://user-images.githubusercontent.com/86804513/156225546-f0ff0b23-f491-4aed-a288-ab80efecd2c5.jpeg" width="300">

**Comment by karunakaran186** [comment]
Go ahead!!! Ping me 8754659759
