### ISSUE TITLE
Take A Break Project

### ISSUE THREAD

**Issue by SwarupKMondal** [karunakaran186/KAVI-voice-Assitant#128]
We all are so much busy in our work so I will make a reminder so that after every 30 minutes it will open a YouTube video for some relaxation.

I am a Gssoc'22 Participant.
I would like to work in this issue.
Please assign it to me Sir

**Comment by karunakaran186** [comment]
sure!!! you can work on that issue

**Comment by karunakaran186** [comment]
good work keep contributing more!!!! 🥉
