### ISSUE TITLE
Adding Where is command, adding temperature and humidity in  weather 

### ISSUE THREAD

**Issue by Aniket11007** [karunakaran186/KAVI-voice-Assitant#20]
Expected Output:
User: Kavi where is xyz Place 
Kavi:This place is loacated at some xyz

For weather:
user :kavi weather in mumbai
kavi: Temperature in kelvin unit is
         humidity in percentage is
         Description

**Comment by karunakaran186** [comment]
Awesome work bro!!!! 


:) @Aniket11007
