### ISSUE TITLE
Screen-recorder

### ISSUE THREAD

**Issue by Phoenix-031** [karunakaran186/KAVI-voice-Assitant#23]
Kavi will start recording screen when commanded to do so and save it in a destined directory

I would like to work on this feature for @GSSOC 22'

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if this issue is still not resolved. Thanks.

**Comment by tasneemahmed123** [comment]
hi , i want to work on this issue if still opened , i will add ascreen recorder to voice assistant on awebsite to record each voice
