### ISSUE TITLE
Converting Kavi to an executable file 

### ISSUE THREAD

**Issue by thebhavana** [karunakaran186/KAVI-voice-Assitant#24]
To Convert Kavi as an executable file i.e. with .exe extension.

Do assign this issue under Gssoc'22.

**Comment by karunakaran186** [comment]
Really an Awesome idea @thebhavana 

yeah....you can make it!!!!

**Comment by karunakaran186** [comment]
ping me on:-(8754659759)

**Comment by karunakaran186** [comment]
hello @thebhavana ji a small remainder about your issue :)
