### ISSUE TITLE
Adding exit command and Enhancing def_takecommand() 

### ISSUE THREAD

**Issue by Aniket11007** [karunakaran186/KAVI-voice-Assitant#27]
--> Adding Exit  command  Where user can stop Kavi from functioning by saying exit or stop command.
--> Enhancing def_takecommand function (Some changes required in try catch block) to perform more interactively with user.

Consider this issue under GSSOC 22

**Comment by karunakaran186** [comment]
wonderfull idea bro feel free to ping me we shall discuss in discord

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if this issue hasn't been resolved. Thanks.

**Comment by karunakaran186** [comment]
thank you for contribution :)
