### ISSUE TITLE
issues(gssoc 2022)

### ISSUE THREAD

**Issue by karunakaran186** [karunakaran186/KAVI-voice-Assitant#3]
Raise an Issue before making an PR

**Comment by Krishna841** [comment]
Hi! I would like to update the readme to embed the demo video and also provide contributing guidelines. Can you assign that to me?

**Comment by karunakaran186** [comment]
> Hi! I would like to update the readme to embed the demo video and also provide contributing guidelines. Can you assign that to me?

Yeah sure....happy to work with you...

**Comment by karunakaran186** [comment]
Sure...😊🤗
