### ISSUE TITLE
Fix Readme 

### ISSUE THREAD

**Issue by chinmay29hub** [karunakaran186/KAVI-voice-Assitant#30]
Improve readme by fixing the technology sections badge tag. Also improve the hyperlinks with adding text instead of full links. Adding some more info about libraries used. Adding gifs to make the readme baeutiful.

**Comment by chinmay29hub** [comment]
Hello @karunakaran186, please assign this issue to me I would like to contribute.

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me; if this task is not resolved yet. Thanks.

**Comment by karunakaran186** [comment]
issue solved
