### ISSUE TITLE
Capture images using Camera 

### ISSUE THREAD

**Issue by amgad-div** [karunakaran186/KAVI-voice-Assitant#31]
To capture the image using webcam using Python Assistant, ecapture module of python is implemented
Please assign this issue to me

**Comment by amgad-div** [comment]
if image contian a text we can translate it

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if the issue is not resolved. Thanks.

**Comment by amgad-div** [comment]
i am working on it
