### ISSUE TITLE
KAVI voice assistant tells jokes

### ISSUE THREAD

**Issue by ranimanya** [karunakaran186/KAVI-voice-Assitant#37]
Hello! I am eager to contribute this feature in the KAVI voice assistant. It will generate random jokes like "Joke of the day".

I'm a Gssoc'22 participant. Please assign me this issue @karunakaran186   :-):-):-)

**Comment by karunakaran186** [comment]
Pyjokes module were already used

It will also generate random jokes
Rather than pyjokes you know

Le me proceed

Thank you for showing interest on my prj

**Comment by ranimanya** [comment]
Can I come up with another issue? @karunakaran186

**Comment by karunakaran186** [comment]
Of course you can!
