### ISSUE TITLE
Feature Add- Image Requests

### ISSUE THREAD

**Issue by AlapanDas** [karunakaran186/KAVI-voice-Assitant#4]
This feature will fetch Images with user-defined tags from the public image library (hence usable for creative  purposes ) , it will also provide the user with image quality control such as HD,FHD,2K,4K..etc. I faced a lot of problems while designing an app, collecting random pictures i think this might help some developers like me who is amateur in this field and also requires a simple interface to carry.
Assign me this work for @GSSOC 22'

**Comment by karunakaran186** [comment]
Nice Idea @GSSOC 22'
