### ISSUE TITLE
add coin flip and choose a random number feature

### ISSUE THREAD

**Issue by jeevanalok** [karunakaran186/KAVI-voice-Assitant#42]
I want to implement a feature when we say flip a coin, it should respond to a head or tail and also for those times we want to choose a random number for when we can't make up our mind.
For ex- hey kavi! flip a coin
           Kavi:- sure! You got heads!
          hey kavi! choose a number between 1-25! be quick!
          Kavi: Well, 17 seems a nice one isn't it.

I am a GSSOC participant and want to work on this aspect @karunakaran186

**Comment by karunakaran186** [comment]
Too good go ahead!

**Comment by jeevanalok** [comment]
Could you assign me to this project so that i acn start @karunakaran186
