### ISSUE TITLE
Update-Readme.md

### ISSUE THREAD

**Issue by AnonymousCodes911** [karunakaran186/KAVI-voice-Assitant#5]
*To update the readme and adding basic guides to contribute in this project 

Kindly assign this to me. 

signed off by _youteakay <backuputk@gmail.com>

**Comment by karunakaran186** [comment]
If Kavi get customized with good readme she will be happy!!!

**Comment by shivanithorve01** [comment]
I would like to contribute too . @karunakaran186 please assign it to me

**Comment by Charu2510** [comment]
Can I contribute in this?

**Comment by karunakaran186** [comment]
Yes, you can do that. Ping me on whatsapp 8754659759

**Comment by akritimangal** [comment]
I would like to make changes in README. I can customize Readme into either the formal technical version or into a casual informal version. Please assign this task to me and do tell me which version you will like the most. @karunakaran186 
Signing off-- akritimangal@gmail.com
