### ISSUE TITLE
Volume control feature and battery status feature

### ISSUE THREAD

**Issue by shrey2003** [karunakaran186/KAVI-voice-Assitant#52]
### Description

I want to add volume control feature so that user can control volume just by saying volume up and down and battery status feature which can tell the user about his battery status. Please assign the task to me @karunakaran186. I am a GSSOC'22 participant.

### Domain

Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shrey2003** [comment]
Please update the label to gssoc 2022

**Comment by karunakaran186** [comment]
Cool you can go ahead wonderful feature !!! :)

**Comment by shrey2003** [comment]
Sir please update the label to gssoc 2022  @karunakaran186

**Comment by karunakaran186** [comment]
updated label issue solved!!! :)
