### ISSUE TITLE
[Create New Issue]: sh: 1: aplay: not found

### ISSUE THREAD

**Issue by chinmay29hub** [karunakaran186/KAVI-voice-Assitant#54]
### Description

we get the below error when we run it on linux.

```
sh: 1: aplay: not found
hello iam kavi Voice assistant
sh: 1: aplay: not found
How are you buddy!!!
sh: 1: aplay: not found
doing good right?????
sh: 1: aplay: not found
think so good
sh: 1: aplay: not found
what can i do for you buddy
None
```

### Domain

Python_Domain

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by chinmay29hub** [comment]
@karunakaran186 please assign me this issue I would like to do some research on how we can fix the above error.

**Comment by karunakaran186** [comment]
Go ahead! :)

**Comment by anipaul2** [comment]
Assign this to me also ...I would like to contribute , gssoc'22 participant

**Comment by karunakaran186** [comment]
Thanks for contributing :)
