### ISSUE TITLE
OSError: libespeak.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by chinmay29hub** [karunakaran186/KAVI-voice-Assitant#55]
### We get following error on specifically on ubuntu:
![Screenshot-20220304223610-1632x941](https://user-images.githubusercontent.com/69494946/156808732-7e463ae1-3e7e-4002-a974-c661a223cbcb.png)

**Comment by chinmay29hub** [comment]
@karunakaran186 please assign me this issue. I want to do research on how we can counter this problem for our ubuntu users.

**Comment by karunakaran186** [comment]
oh!

**Comment by TheCreaToR-01** [comment]
Just install espeak library to tackle this problem

Command - " sudo apt install libespeak "

@chinmay29hub
