### ISSUE TITLE
Adding a voice translator in Kavi

### ISSUE THREAD

**Issue by KIET7UKE** [karunakaran186/KAVI-voice-Assitant#6]
Hey bro, As I talked to you about the voice translator feature I want to contribute to this. So please assign me this.

**Comment by karunakaran186** [comment]
Nice one!!!!!
go ahead bro

**Comment by Aniket11007** [comment]
So is this project is open for gssoc 22? I would love to contribute and add some more functionality to it

**Comment by amgad-div** [comment]
Hey bro,I would love to contribute and add some more functionality to it with you.

**Comment by Preksha2505** [comment]
Hello, I would really like to work on this and contribute in this issue .

**Comment by karunakaran186** [comment]
go ahead bro ping me on this num(8754659759)

**Comment by karunakaran186** [comment]
ping me on (8754659759)

**Comment by tasneemahmed123** [comment]
I loved this, so please, assign me this issue

**Comment by karunakaran186** [comment]
Yup sure ping me 8754659759
