### ISSUE TITLE
Security Feature Like breaking glass detection, smoke alarms detection

### ISSUE THREAD

**Issue by Shreya-spec** [karunakaran186/KAVI-voice-Assitant#60]
I want to add security features . When this option is enabled, it can send you notifications if your Echo detects certain sounds such as smoke alarms or breaking glass. Please assign the task to me @karunakaran186. I am a GSSOC'22 participant.

**Comment by Shreya-spec** [comment]
I want to add security features . When this option is enabled, it can send you notifications if your Echo detects certain sounds such as smoke alarms or breaking glass. Please assign the task to me @karunakaran186. I am a GSSOC'22 participant.

**Comment by karunakaran186** [comment]
nice feature!!! :) go ahead

**Comment by Shreya-spec** [comment]
> nice feature!!! :) go ahead

Thanks

**Comment by karunakaran186** [comment]
ping me @Shreya-spec 8754659759
