### ISSUE TITLE
Greeting 

### ISSUE THREAD

**Issue by ayush-agarwal-190** [karunakaran186/KAVI-voice-Assitant#61]
I wanted to add a greeting function which will greet the user according to time .Like if it is morning time it will say Good morning And if its Evening time  It will say Good evening ,etc

**Comment by ayush-agarwal-190** [comment]
Please assign me the Greeting task ..

**Comment by karunakaran186** [comment]
yes sure!!! go ahead ping me on 8754659759

**Comment by karunakaran186** [comment]
i have merged your PR @ayush-agarwal-190 so i shall be closing you issues bro!!! :))

Keep contributing 💯
