### ISSUE TITLE
updating requirements.txt

### ISSUE THREAD

**Issue by jeevanalok** [karunakaran186/KAVI-voice-Assitant#65]
![ss1](https://user-images.githubusercontent.com/40180496/156885909-4c9593f5-7b9c-43c3-bc1c-b85b1fd0a566.png)
![ss2](https://user-images.githubusercontent.com/40180496/156885917-17370898-786e-4f0c-86f9-c2284af2d31e.png)
![ss3](https://user-images.githubusercontent.com/40180496/156887376-33ccb0bc-bf8e-4716-80f1-157d103cceab.png)

The above modules are absent in the requirements.txt file which are essential for program to run

Please assign me under GSSOC'22 to update the file @karunakaran186

**Comment by karunakaran186** [comment]
ping me on discord :) @jeevanalok

**Comment by jeevanalok** [comment]
> ping me on discord :) @jeevanalok

Sent you msg
