### ISSUE TITLE
Adding "Trending Movies" command

### ISSUE THREAD

**Issue by Aniket11007** [karunakaran186/KAVI-voice-Assitant#72]

**Comment by karunakaran186** [comment]
Go ahead!!! :)

**Comment by coolblizzarts** [comment]
Hello Payal here, I would like to contribute to this issue. Can you please assign it to me. Regards.

**Comment by karunakaran186** [comment]
Hello Karan here!
Yes sure payal contact me via whatsapp no 8754659759 . Before working on to project....glad to work on my project !!!
