### ISSUE TITLE
Email_Sender 

### ISSUE THREAD

**Issue by ayush-agarwal-190** [karunakaran186/KAVI-voice-Assitant#74]
Can I make a function to take command and send a mail .
Making A sendEmail() function which will help us send emails to one or more than one recipient.
Simple Mail Transfer Protocol (SMTP) is a protocol that allows us to send emails and route emails between mail servers.

**Comment by ayush-agarwal-190** [comment]
Please assign me the task ,I want to work on this topic.

**Comment by karunakaran186** [comment]
Go ahead!!! :) expecting this feature
