### ISSUE TITLE
Navigate to location and Tell current date or time

### ISSUE THREAD

**Issue by PurvajaDurga** [karunakaran186/KAVI-voice-Assitant#78]
Hi @karunakaran186 ,
I would like to add a feature where a user tells the location then a location is pointed out in google maps.
And Display the date or time or day.

**Comment by karunakaran186** [comment]
future already added.... :)

**Comment by karunakaran186** [comment]
ping me @PurvajaDurga  8754659759
 
after than you can work for this project :)
