### ISSUE TITLE
if there is no word document in the system, it is raising the error and shutting down immediately

### ISSUE THREAD

**Issue by ShamithaReddy** [karunakaran186/KAVI-voice-Assitant#81]
1. If there is no Notepad in the system, it is raising the error and shutting down immediately, instead it should try to talk about the issue and then move to the next phase.
2. There is another issue while loading word document, in some systems it is stored as WINWORD.EXE but in others it is stored as WordPad.EXE, so instead of telling about the error in this case, it should try to locate word pad as WordPad.EXE, if it is also not present in the system, then raise the error.
![image](https://user-images.githubusercontent.com/73388412/156989057-56580f27-c11b-4ecd-bc81-ba11ef95ca7c.png)

I'm a GSSOC Contributor, Kindly assign this issue to me.
Thankyou.

**Comment by karunakaran186** [comment]
go ahead!!! noteable feature!!! :)

**Comment by karunakaran186** [comment]
ping me @8754659759
