### ISSUE TITLE
Use of  Wolfram Alpha

### ISSUE THREAD

**Issue by AlapanDas** [karunakaran186/KAVI-voice-Assitant#88]
Wolfram Alpha(https://developer.wolframalpha.com/) is a excellent API, and using that will enhance user experience and develop our assistant much better.
Please assign me for this issue as @GSSOC 2022' and kindly add a apt level for this.
@karunakaran186

**Comment by karunakaran186** [comment]
go ahead bro!!!! :) @AlapanDas
