### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by adii21-Ux** [karunakaran186/KAVI-voice-Assitant#91]
Some statements in code is out of function and can be confusing.

**Comment by adii21-Ux** [comment]
@karunakaran186 assign this to me please

**Comment by karunakaran186** [comment]
Go ahead!!! :)) @adii21-Ux 

https://www.linkedin.com/in/karuna-karan-vijayaraghavan-622a2a218/
contact me via linkedIN

**Comment by karunakaran186** [comment]
modularity done :) come up with another issues :)
