### ISSUE TITLE
Adding date time feature in the voice assistant

### ISSUE THREAD

**Issue by pabak2002** [karunakaran186/KAVI-voice-Assitant#92]
pls assign this task to me and allow me to do it plsss. I am a GSSOC'22 contributor.

**Comment by Rajkushwaha26** [comment]
"Hi, I am Raj Kushwaha, a contributor to GSSOC  2022. I would like to work on this issue.So please assign this issue to me

**Comment by karunakaran186** [comment]
what are you going to do can you describe in brief !!! :))

**Comment by pabak2002** [comment]
> what are you going to do can you describe in brief !!! :))

As of now it just wishes according to the time as good morning or good afternoon.....if u wish to add some more funcionality based on this date and time pls tell me and i will give it a try to implement it

**Comment by pabak2002** [comment]
<img width="944" alt="Screenshot 2022-03-10 144248" src="https://user-images.githubusercontent.com/86981196/157629417-b0e3f2b3-a618-4a3a-a2ae-a67545c2898b.png">



Why cant i register a pr??
Can u help me as i am new to it.

**Comment by karunakaran186** [comment]
Ping me in discord

**Comment by pabak2002** [comment]
@karunakaran186 can u see my commits i made in the file code.py.???.....kindly merge it

**Comment by karunakaran186** [comment]
nope vro!

**Comment by karunakaran186** [comment]
already done bro!!!! so come up with any-other issues!!! :) 👍🏻

**Comment by pabak2002** [comment]
I mean did my contribution count atlast  or is it that someone else has already done it and u want me to do something else??
