### ISSUE TITLE
Changing the structure.

### ISSUE THREAD

**Issue by Praj-17** [karunakaran186/KAVI-voice-Assitant#94]
Hello sir, I have previously worked on a similar project and have really good experience in it. You can visit my entire code here.https://github.com/Praj-17/AI---Project

I have the following suggestions.

- Change the if-else structure to an intent.json file
- add a print statement within the talk function. So that we need not implement print every time.
- Add natural language processing. the current version is super hard-codded. 
- We can add object detection and navigation parts as well
- Also can implement an activation word that will need to call whenever we want one command to get executed.

**Comment by Praj-17** [comment]
Waiting fro quick assignment.

**Comment by Praj-17** [comment]
I am GSSOC'22 Particiapnt

**Comment by karunakaran186** [comment]
Glad sir!! you can go-ahead :) 👍🏻
